  services:
    de_und_en:
      platform: linux/amd64
      build:
        context: .
        dockerfile: Dockerfile
      container_name: de_und_en
      working_dir: /app
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
